<?php
$z[0]=Array("arcurl","",47,62);
$z[0][4]=array();
$z[1]=Array("title","",89,103);
$z[1][4]=array();
$z[2]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<img width='80' height='60' src='{@me['litpic']}' class='icon wp-post-image' alt='{@me['title']}' title='{@me['title']}' />\"); ",106,323);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",338,353);
$z[3][4]=array();
$z[4]=Array("title","",380,394);
$z[4][4]=array();
$z[5]=Array("title","",397,411);
$z[5][4]=array();
$z[6]=Array("pubdate","",441,488);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y/m/d',@me)";

?>