<?php
$z[0]=Array("typeurl","",64,80);
$z[0][4]=array();
$z[1]=Array("typename","",102,119);
$z[1][4]=array();
$z[2]=Array("arcurl","",173,188);
$z[2][4]=array();
$z[3]=Array("title","",209,223);
$z[3][4]=array();
$z[4]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"\r\n      <div class='viewimg'> <a href='{@me['arcurl']}' title='{@me['title']}' target='_ablank' class='ipic'> <img src='{@me['litpic']}' alt='{@me['title']}' class='thumbnail' /><span class='shine' style='background-position: 160px 50%;'> </span></a> </div>\r\n      \"); ",273,633);
$z[4][4]=array();
$z[4][4]['runphp']="yes";
$z[5]=Array("description","",663,713);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,600)";
$z[6]=Array("pubdate","",790,835);
$z[6][4]=array();
$z[6][4]['function']="MyDate('m-d',@me)";
$z[7]=Array("arcurl","",890,905);
$z[7][4]=array();
$z[8]=Array("click","",1009,1023);
$z[8][4]=array();
$z[9]=Array("arcurl","",1073,1088);
$z[9][4]=array();
$z[10]=Array("title","",1097,1111);
$z[10][4]=array();

?>