<?php
$z[0]=Array("global","",286,314);
$z[0][4]=array();
$z[0][4]['name']="cfg_indexname";
$z[1]=Array("global","",408,434);
$z[1][4]=array();
$z[1][4]['name']="cfg_logotxt";
$z[2]=Array("global","",622,645);
$z[2][4]=array();
$z[2][4]['name']="cfg_txqq";
$z[3]=Array("global","",757,781);
$z[3][4]=array();
$z[3][4]['name']="cfg_weibo";
$z[4]=Array("global","",883,908);
$z[4][4]=array();
$z[4][4]['name']="cfg_tweibo";
$z[5]=Array("global","",1596,1621);
$z[5][4]=array();
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channelartlist","\r\n          <li class=\"menu-item \"><a href=\"{dede:field name=\"typeurl\"/}\">{dede:field name=\"typename\"/}</a>\r\n            <ul class=\"sub-menu\">\r\n              {dede:channel type=\"son\"}\r\n              <li class=\"menu-item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",2445,2863);
$z[6][4]=array();
$z[6][4]['typeid']="top";
$z[6][4]['row']="18";
$z[7]=Array("global","",3001,3026);
$z[7][4]=array();
$z[7][4]['name']="cfg_notice";

?>