<?php
$z[0]=Array("sql","[field:dd/]",641,738);
$z[0][4]=array();
$z[0][4]['sql']="SELECT SUM(click) AS dd FROM dede_archives where channel=1";
$z[1]=Array("arclist","\r\n        <li>\r\n          <div class=\"sideshow\"><a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> [field:array runphp='yes']@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<img width='80' height='60' src='{@me['litpic']}' class='icon wp-post-image' alt='{@me['title']}' title='{@me['title']}' />\"); [/field:array] </a> <a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> [field:title/] </a> <span class=\"datetime\"> [field:pubdate function=\"MyDate('Y/m/d',@me)\"/] </span> </div>\r\n        </li>\r\n        ",1021,1611);
$z[1][4]=array();
$z[1][4]['row']="5";
$z[1][4]['titlelen']="100";
$z[2]=Array("arclist","\r\n        <li>\r\n          <div class=\"sideshow\"><a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> [field:array runphp='yes']@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<img width='80' height='60' src='{@me['litpic']}' class='icon wp-post-image' alt='{@me['title']}' title='{@me['title']}' />\"); [/field:array] </a> <a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> [field:title/] </a> <span class=\"datetime\"> [field:pubdate function=\"MyDate('Y/m/d',@me)\"/] </span> </div>\r\n        </li>\r\n        ",1813,2403);
$z[2][4]=array();
$z[2][4]['row']="5";
$z[2][4]['titlelen']="100";
$z[3]=Array("tag"," <a href=\"/plus/search.php?q=[field:tag /]\"  target=\"_blank\" title=\"[field:tag /]\" class=\"tag-link-9\" >[field:tag /]</a> ",2617,2768);
$z[3][4]=array();
$z[3][4]['row']="40";
$z[4]=Array("flink","\r\n        <li>[field:link /]</li>\r\n        ",2880,2982);
$z[4][4]=array();
$z[4][4]['titlelen']="16";
$z[4][4]['row']="6";
$z[4][4]['type']="text";
$z[5]=Array("type","[field:ID function='GetTotalArc(@me)'/] ",4198,4275);
$z[5][4]=array();
$z[5][4]['typeid']="6";
$z[6]=Array("type","[field:ID function='GetTotalArc(@me)'/] ",4286,4363);
$z[6][4]=array();
$z[6][4]['typeid']="8";
$z[7]=Array("type","[field:ID function='GetTotalArc(@me)'/] ",4374,4451);
$z[7][4]=array();
$z[7][4]['typeid']="1";

?>